spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrental
    username: ${POSTGRES_USER:carrental}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO